
// Action types of the library
export const API_SET_AXIOS_CONFIG = 'API_SET_AXIOS_CONFIG'
export const API_HYDRATE = 'API_HYDRATE'
export const API_WILL_CREATE = 'API_WILL_CREATE'
export const API_CREATED = 'API_CREATED'
export const API_CREATE_FAILED = 'API_CREATE_FAILED'
export const API_WILL_READ = 'API_WILL_READ'
export const API_READ = 'API_READ'
export const API_READ_FAILED = 'API_READ_FAILED'
export const API_WILL_UPDATE = 'API_WILL_UPDATE'
export const API_UPDATED = 'API_UPDATED'
export const API_UPDATE_FAILED = 'API_UPDATE_FAILED'
export const API_WILL_DELETE = 'API_WILL_DELETE'
export const API_DELETED = 'API_DELETED'
export const API_DELETE_FAILED = 'API_DELETE_FAILED'
